### ISSUE TITLE
Improve stability by implementing automatic testing

### ISSUE THREAD

**Issue by danylevskyi** [jet-dev-team/drupal-dockerizer#24]
Currently, the development branch is rapidly evolving. While adding new features and enhancements we often adding regressions. Now I think we've reached the critical line. I propose to start implementing the automated testing.

It would be really great to have a first quick test which just installs a fresh Drupal project from scratch.  I think this test should mimic the quickstart tutorial for the newcomers.

A quick overview of what could be tested:

-  create a directory structure
-  create Drupal project with composer
-  install a fresh site
-  make sure Drupal has been installed successfully

I'd start with Github Actions.

 - [x] Implement basic test for installing new Drupal #25
 - [x] Implement basic test for using existing database #26
 - [x] Implement test for SSL configuration #30
 - [x] Implement test for spinning up multiple environments #32
 - [x] Implement test for Drupal Solr functionality #43
